trigger: none

pr: none

parameters:

- name: terraformAction
  displayName: "Terraform Action"
  type: string
  default: plan

  values:
  - plan
  - apply

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

#Install Terraform
- task: AzureCLI@2
  displayName: Install Terraform
  inputs:
    azureSubscription: 'sp_github'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      unzip -o terraform_1.9.8_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version

#Init
- task: AzureCLI@2
  displayName: Terraform Init
  inputs:
    azureSubscription: 'sp_github'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init

#Validate
- task: AzureCLI@2
  displayName: Terraform Validate
  inputs:
    azureSubscription: 'sp_github'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform validate

#PLAN
- task: AzureCLI@2
  displayName: Terraform Plan
  condition: eq('${{ parameters.terraformAction }}','plan')
  inputs:
    azureSubscription: 'sp_github'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform plan

#APPLY
- task: AzureCLI@2
  displayName: Terraform Apply
  condition: eq('${{ parameters.terraformAction }}','apply')
  inputs:
    azureSubscription: 'sp_github'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform apply -auto-approve
